### ISSUE TITLE
Fill doesn't work when switching back to brush

### ISSUE THREAD

**Issue by pjlao307** [nelsonjchen/tool4comma10k#3]
After you fill areas with color when you switch back to brush all the filled areas get unfilled.
This also happens when you click Save though the saved file does have the filled colors in it.

**Comment by nelsonjchen** [comment]
Oof! The filling functionality uses the old path stuff which I removed the codepath for. I am usually tweaking atop the old mask so fill isn't as useful.

**Comment by nelsonjchen** [comment]
Huh! I can't see how fills ever worked in the original. https://github.com/nelsonjchen/comma10k/blob/d079071751402dc7e17ec70c8273f85f61bf4e59/pencil/static/js_pencil.js

Hmm, I'll try to implement it.
