### ISSUE TITLE
Saved files are large

### ISSUE THREAD

**Issue by pjlao307** [nelsonjchen/tool4comma10k#4]
They appear to be about 300% larger in size than the original mask file.

**Comment by nelsonjchen** [comment]
The browser generates these PNG files. I'm going to guess the browsers won't compress the PNGs well. I'm not sure what to do here hmm. Is there some form of portable png-crush utility?

**Comment by nelsonjchen** [comment]
Also they might be PNG24 instead of PNG8.

**Comment by nelsonjchen** [comment]
I'll see if I can put this in and try to call out to it: https://github.com/shssoichiro/oxipng .
