### ISSUE TITLE
Other files being modified after saving image

### ISSUE THREAD

**Issue by pjlao307** [nelsonjchen/tool4comma10k#5]
When saving the image to local repo it's modifying other files besides the image:
![image](https://user-images.githubusercontent.com/3270869/76204609-f411bf00-61b5-11ea-860d-026b6be4ac82.png)

**Comment by nelsonjchen** [comment]
That is strange! Did the line endings change or something?

**Comment by pjlao307** [comment]
Looks like it.
![image](https://user-images.githubusercontent.com/3270869/76204974-9f227880-61b6-11ea-9a80-a62fbc128420.png)

**Comment by nelsonjchen** [comment]
Huh! That really makes no sense to me. Save to Disk only has one file write call.  It might be the `Reset Current to Upstream` functionality that is causing this.

**Comment by nelsonjchen** [comment]
Is it possible you're looking at the Git repository cloned by GitHub Desktop or Git on Windows from Git in Ubuntu/WSL? Repositories cloned by GitHub Desktop or Git on Windows might checkout the text files with CRLF line endings on default settings which makes Ubuntu/WSL Git freak out.

**Comment by pjlao307** [comment]
This was a repo cloned by Windows subsystem for Linux.

**Comment by nelsonjchen** [comment]
Interesting! Ok. `Reset Current to Upstream` is using `git` from Git on Windows and its implementation is probably checking these out with CRLF.

**Comment by nelsonjchen** [comment]
I think what I'll do is this. It's a bit invasive already but we're using Windows in 2020 and even `notepad.exe` supports LF nowadays. I'm going to set `core.autocrlf` to false on the repo before doing the rest of `Reset Current to Upstream`.

**Comment by nelsonjchen** [comment]
![image](https://user-images.githubusercontent.com/5363/76283592-3db2e600-6258-11ea-9744-411b9268aaaf.png)

Good news is I'm able to reproduce your issue.

**Comment by nelsonjchen** [comment]
![image](https://user-images.githubusercontent.com/5363/76283648-63d88600-6258-11ea-8fc2-f96634c1e2e9.png)

Git for Windows for contrast
